name: Buddy
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <=3.1.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.0.2
  injectable: ^2.3.0
  flutter_iconly: ^1.0.2
  get_it: ^7.6.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  flutter_bloc: ^8.1.3
  skeletonizer: ^0.7.0
  animations: ^2.0.7
  url_launcher: ^6.1.14
  animated_digit: ^3.2.3
  flutter_cached_pdfview: ^0.4.2
  firebase_storage: ^11.2.6
  shared_preferences: ^2.2.0
  bloc_concurrency: ^0.2.2
  date_time_format: ^2.0.1
  animate_to: ^0.1.0
  firebase_core: ^2.15.1
  path_provider: ^2.1.1
  another_flushbar: ^1.12.30
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.3
  build_runner: ^2.3.3
  freezed: ^2.4.2

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/cfg/
    - assets/svgs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Regular.otf
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 400
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 700
        - asset: assets/fonts/Satoshi-Italic.otf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
